### ISSUE TITLE
I wonder if you could give me some pictures

### ISSUE THREAD

**Issue by KylinskyChen** [surt91/hk_tree#1]
![image](https://user-images.githubusercontent.com/30420247/138555205-35a284b0-e4e8-49b3-96b9-d1ba201cfc6d.png)

![image](https://user-images.githubusercontent.com/30420247/138555215-98cfe678-ec58-446c-aa7e-8b5f28880196.png)

Hello, could you please provide me with the source code of these pictures?  My email is drchenxie@163.com, thanks a million!

**Comment by surt91** [comment]
From the cluster configuration files generated with the program of this repo, the top two plots need a preprocessing step. Its (not very clean) source is available in another repo at <https://github.com/surt91/hk/blob/master/py/legacy/make_eps_range_map.py>. Then the plot script is just:

```python
import json
import lzma

import matplotlib
import matplotlib.pyplot as plt

matplotlib.rc('text', usetex=True)
matplotlib.rc('font', size=9)

with lzma.open("preprocessed_file.json.xz") as f:
    data = json.loads(f.read().decode("utf-8"))

fig = plt.gcf()
fig.set_size_inches(3+3./8, 2.08)

plt.xlabel(r"$\varepsilon_l$")
plt.ylabel(r"$\varepsilon_u$")
plt.grid(b=None)

plt.hist2d(
    data["x"],
    data["y"],
    weights=data["weight"],
    bins=(data["xbins"], data["ybins"]),
    cmap=plt.cm.viridis,
    vmin=0,
    vmax=1,
    cmin=1e-6,  # this will color all cells without entries (eps_l > eps_u ) white
    rasterized=True,
    # norm=matplotlib.colors.LogNorm(),
    # density=True
)

plt.xlim(left=0)
plt.ylim(bottom=0, top=1)

cb = plt.colorbar()
cb.set_label(r'$\left<S\right>$')

plt.tight_layout()

fig.savefig('map.pdf', dpi=300)
```

The bottom two plots are just pretty basic Gnuplot scripts:

```gnuplot
set terminal epslatex standalone size 8.6cm,5.2cm solid header '\\usepackage{amsmath}' font ',9'; set size nosquare
set output "sweep.tex"

set key bottom maxrows 3

set xtics 0.2
set ytics 0.2

set format xy "$%.1f$"

set xl '$\varepsilon_u$'
set yl '$\left< S \right>$' 

p "../data/sweep/d512.dat" w ye pt 12 lc 4 t "$n = 512$", \
  "../data/sweep/d2048.dat" w ye pt 10 lc 3 t "$n = 2048$", \
  "../data/sweep/d8192.dat" w ye pt 8 lc 2 t "$n = 8192$", \
  "../data/sweep/d32768.dat" w ye pt 6 lc 1 t "$n = 32768$", \
  "../data/sweep/d131072.dat" w ye pt 4 lc 0 t "$n = 131072$", \
```

The data files are the same format as the format output by [example.py](../blob/master/example.py) (plus a third column with standard errors).

So, I am curious what you need this for. Let me know what kind of project you are working on.
